### ISSUE TITLE
Misunderstanding of library usage

### ISSUE THREAD

**Issue by Hershel1995** [etsi-cti-admin/robotframework-mockserver#3]
When I use _Create Mock Expectation_ keyword, MockServer returns **Not Mocked** error because it tries to search for a file .mock under _/expectation_ directory. In fact, when I build request and response objects and pass them to _Create Mock Expectation_ keyword, I have the following log in MockServer terminal:

```
$ mockserver -p 8081 -m .
Mockserver serving mocks {verbose:true} under "." at http://localhost:8081
Reading from expectation/PUT--{"times": {"remainingTimes": 1, "unlimited": true}, "httpResponse": {"statusCode": 200}, "httpRequest": {"method": "GET", "path": "/myEndpoint"}}.mock file: Not matched
```

In my robot test, I have the following code:
```
Test
    &{req}=  Create Mock Request Matcher  GET  /myEndpoint
    &{rsp}=  Create Mock Response  status_code=200
    Create Mock Expectation  ${req}  ${rsp}
```

and the test fails on _Create Mock Expectation_ keyword.
In addition, I noticed that even if I use keywords _Reset All Requests_ and _Verify Mock Expectation_, I have the same **Not Mocked** error, because MockServer tries to search respectively for _reset/PUT.mock_ and _verify/PUT.mock_. Do I have to create these mock files? And how?

P.S.: I state that I'm using only the MockServerLibrary, without provided docker, I have MockServer installed in local on my machine and I have imported the library in my robot test suite.
Thanks.

**Comment by Hershel1995** [comment]
It seems that using docker image provided by official site, the keywords work properly. Can someone confirm that using a local installation of MockServer the library has some issues as described above?

**Comment by michele-carignani** [comment]
Hi @Hershel1995 ! 

Sorry for the late reply. This issue seems more related to https://github.com/mock-server/mockserver than the library, since the issue is only with local installation of mockserver. (Maybe permissions issue in the folder where you execute the binary?)

Moreover I could not replicate the issue. I executed locally via

    java -jar mockserver-netty-5.11.1-jar-with-dependencies.jar -serverPort 1080

and successfully executed the library.
